apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chatapp-namespace
type: Opaque
stringData:
  jwt: "bce16cf7eafefcfad5554d818cc8a99f7a7798326fe315154fb55fce0021181f"
  mongouri: "mongodb://root:root@mongodb-service:27017/chatApp?authSource=admin&retryWrites=true&w=majority"
  mongodb_username: "root"
  mongodb_password: "root"


  # password: {{ .Values.password | b64enc }}